### ISSUE TITLE
chrome.promise.storage.local.get not work

### ISSUE THREAD

**Issue by Xrymz** [tfoxy/chrome-promise#1]
```
chrome.promise = new ChromePromise();
function get(key) {
    return chrome.promise.storage.local.get(key);
}
```

```
TypeError: Cannot read property 'functionSchemas' of null
    at self.(anonymous function) (extensions::StorageArea:26:27)
    at setPromiseFunction (chrome-extension://***/assets/chrome-promise/chrome-promise.js:47:25)
    at Object.setPromiseFunction [as get] (chrome-extension://***/assets/chrome-promise/chrome-promise.js:35:24)
```

**Comment by tfoxy** [comment]
Thanks for opening the issue. Tomorrow I will try to reproduce and fix the error.

**Comment by tfoxy** [comment]
I had some spare time today to fix the issue. Try the new version.

**Comment by Xrymz** [comment]
work, perfect. thx!
